use std::{fs, path::Path};

use crate::{compile::compile_repo, hook::install_pre_commit_hook, util::paths::find_repo_root};

const DEFAULT_TENETRC: &str = r#"[defaults]
grace_days = 90
priority = "normal"

[compile]
header = "<!-- generated by tenet from .context/ — do not edit directly -->"
include_stale = true
segregate_stale = true

[lint]
check_secrets = true
check_filenames = true

[hook]
install_pre_commit = true
"#;

const EXAMPLE_RULE: &str = r#"---
scope: "**"
priority: normal
---
Delete this file after reading it.

This is an example tenet. Tenets are short statements of truth about your
codebase that you want every AI agent session to know. Create new ones with
`tenet add <type>`.

Types:
- invariants: must-not-change facts
- conventions: team defaults
- decisions: dated choices with reasoning
- gotchas: pitfalls to avoid
- glossary: domain terms
"#;

pub fn run(force: bool, no_hook: bool) -> anyhow::Result<()> {
    let cwd = std::env::current_dir()?;
    let repo_root = find_repo_root(&cwd)?;

    let context_dir = repo_root.join(".context");
    if context_dir.exists() {
        if !force {
            return Err(crate::error::TenetError::AlreadyInitialized { path: context_dir }.into());
        }
        fs::remove_dir_all(&context_dir)?;
    }

    create_context_layout(&repo_root)?;
    fs::write(repo_root.join(".tenetrc"), DEFAULT_TENETRC)?;
    fs::write(
        repo_root.join(".context/invariants/example.md"),
        EXAMPLE_RULE,
    )?;

    if !no_hook {
        install_pre_commit_hook(&repo_root)?;
    }

    let written = compile_repo(&repo_root, false, false)?;

    println!("initialized tenet in {}", repo_root.display());
    println!("generated {} AGENTS.md file(s)", written.len());

    Ok(())
}

fn create_context_layout(repo_root: &Path) -> anyhow::Result<()> {
    let types = [
        "invariants",
        "conventions",
        "decisions",
        "gotchas",
        "glossary",
    ];

    for rule_type in types {
        let dir = repo_root.join(".context").join(rule_type);
        fs::create_dir_all(&dir)?;
        fs::write(dir.join(".gitkeep"), "")?;
    }

    Ok(())
}
