use std::fs;

use assert_cmd::Command;

#[test]
fn compile_writes_root_agents_with_single_rule() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();

    fs::create_dir_all(root.join(".context/invariants")).expect("mkdir");
    fs::write(
        root.join(".context/invariants/global.md"),
        "---\nscope: \"**\"\n---\nAlways run tests\n",
    )
    .expect("write rule");

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["compile"])
        .assert()
        .success();

    let agents = fs::read_to_string(root.join("AGENTS.md")).expect("read agents");
    assert!(agents.contains("generated by tenet"));
    assert!(agents.contains("Always run tests"));

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["compile"])
        .assert()
        .success();

    let agents_again = fs::read_to_string(root.join("AGENTS.md")).expect("read agents");
    assert_eq!(agents, agents_again);
}
