use std::fs;

use assert_cmd::Command;

#[test]
fn init_scaffolds_repo_and_prevents_second_init_without_force() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();

    Command::new("git")
        .current_dir(root)
        .args(["init"])
        .assert()
        .success();

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["init"])
        .assert()
        .success();

    for rule_type in [
        "invariants",
        "conventions",
        "decisions",
        "gotchas",
        "glossary",
    ] {
        assert!(root.join(".context").join(rule_type).exists());
        assert!(root
            .join(".context")
            .join(rule_type)
            .join(".gitkeep")
            .exists());
    }

    assert!(root.join(".tenetrc").exists());
    assert!(root.join(".git/hooks/pre-commit").exists());

    let agents = fs::read_to_string(root.join("AGENTS.md")).expect("read agents");
    assert!(agents.contains("generated by tenet"));

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["init"])
        .assert()
        .code(1);
}
