use std::fs;

use assert_cmd::Command;

#[test]
fn compile_overwrites_existing_generated_agents_file() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();

    fs::create_dir_all(root.join(".context/invariants")).expect("mkdir");
    fs::write(
        root.join(".context/invariants/global.md"),
        "---\nscope: \"**\"\n---\nFresh rule\n",
    )
    .expect("write rule");

    fs::write(
        root.join("AGENTS.md"),
        "<!-- generated by tenet from .context/ — do not edit directly -->\nold\n",
    )
    .expect("write stale generated");

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["compile"])
        .assert()
        .success();

    let updated = fs::read_to_string(root.join("AGENTS.md")).expect("read agents");
    assert!(updated.contains("Fresh rule"));
}

#[test]
fn compile_refuses_handwritten_agents_with_no_marker() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();

    fs::create_dir_all(root.join(".context/invariants")).expect("mkdir");
    fs::write(
        root.join(".context/invariants/global.md"),
        "---\nscope: \"**\"\n---\nFresh rule\n",
    )
    .expect("write rule");

    fs::write(root.join("AGENTS.md"), "# hand written\n").expect("write handwritten");

    Command::cargo_bin("tenet")
        .expect("bin")
        .current_dir(root)
        .args(["compile"])
        .assert()
        .failure();
}
