use std::{fs, path::Path};

use crate::error::TenetError;

/// Compile header marker used to detect tenet-generated `AGENTS.md` files.
pub const GENERATED_HEADER: &str =
    "<!-- generated by tenet from .context/ — do not edit directly -->";

/// Return true when file starts with the configured generated marker line.
pub fn is_generated_agents(path: &Path) -> Result<bool, TenetError> {
    let content = fs::read_to_string(path).map_err(|source| TenetError::Io {
        path: path.display().to_string(),
        source,
    })?;

    Ok(content.is_empty()
        || content
            .lines()
            .next()
            .map(|line| line.starts_with(GENERATED_HEADER))
            .unwrap_or(false))
}
