use std::{
    collections::{HashMap, HashSet},
    fs,
    path::Path,
};

use serde::Deserialize;

use crate::error::TenetError;

/// Top-level tenet configuration loaded from `.tenetrc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TenetConfig {
    /// Default values for rule metadata.
    pub defaults: DefaultsConfig,
    /// Compile-time rendering behavior.
    pub compile: CompileConfig,
    /// Lint behavior settings.
    pub lint: LintConfig,
    /// Hook installation behavior.
    pub hook: HookConfig,
}

impl Default for TenetConfig {
    fn default() -> Self {
        Self {
            defaults: DefaultsConfig::default(),
            compile: CompileConfig::default(),
            lint: LintConfig::default(),
            hook: HookConfig::default(),
        }
    }
}

/// Defaults section from `.tenetrc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DefaultsConfig {
    /// Days after `reviewed` before a rule is stale.
    pub grace_days: i64,
    /// Priority assigned when frontmatter omits it.
    pub priority: String,
}

impl Default for DefaultsConfig {
    fn default() -> Self {
        Self {
            grace_days: 90,
            priority: String::from("normal"),
        }
    }
}

/// Compile section from `.tenetrc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompileConfig {
    /// Header marker for generated files.
    pub header: String,
    /// Include stale rules in compile output by default.
    pub include_stale: bool,
    /// Segregate stale rules into a dedicated section.
    pub segregate_stale: bool,
}

impl Default for CompileConfig {
    fn default() -> Self {
        Self {
            header: String::from(
                "<!-- generated by tenet from .context/ — do not edit directly -->",
            ),
            include_stale: true,
            segregate_stale: true,
        }
    }
}

/// Lint section from `.tenetrc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LintConfig {
    /// Enable secret-pattern scanning.
    pub check_secrets: bool,
    /// Warn on non-kebab-case filenames.
    pub check_filenames: bool,
}

impl Default for LintConfig {
    fn default() -> Self {
        Self {
            check_secrets: true,
            check_filenames: true,
        }
    }
}

/// Hook section from `.tenetrc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HookConfig {
    /// Install the pre-commit hook during init.
    pub install_pre_commit: bool,
}

impl Default for HookConfig {
    fn default() -> Self {
        Self {
            install_pre_commit: true,
        }
    }
}

/// Result of loading `.tenetrc`, including non-fatal warnings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigLoad {
    /// Effective configuration after defaults + overrides.
    pub config: TenetConfig,
    /// Unknown keys found inside known sections.
    pub warnings: Vec<String>,
}

/// Load `.tenetrc` from `repo_root` and merge it with built-in defaults.
///
/// Unknown top-level sections are errors. Unknown keys within known sections are
/// returned as warnings.
pub fn load(repo_root: &Path) -> Result<ConfigLoad, TenetError> {
    let config_path = repo_root.join(".tenetrc");
    if !config_path.exists() {
        return Ok(ConfigLoad {
            config: TenetConfig::default(),
            warnings: Vec::new(),
        });
    }

    let raw = fs::read_to_string(&config_path).map_err(|source| TenetError::Io {
        path: config_path.display().to_string(),
        source,
    })?;

    let parsed: RawTopLevel = toml::from_str(&raw).map_err(|source| TenetError::BadConfig {
        path: config_path.display().to_string(),
        message: source.to_string(),
    })?;

    let mut warnings = Vec::new();
    warnings.extend(check_unknown_keys(
        "defaults",
        parsed.defaults.keys.keys(),
        &["grace_days", "priority"],
    ));
    warnings.extend(check_unknown_keys(
        "compile",
        parsed.compile.keys.keys(),
        &["header", "include_stale", "segregate_stale"],
    ));
    warnings.extend(check_unknown_keys(
        "lint",
        parsed.lint.keys.keys(),
        &["check_secrets", "check_filenames"],
    ));
    warnings.extend(check_unknown_keys(
        "hook",
        parsed.hook.keys.keys(),
        &["install_pre_commit"],
    ));

    let mut merged = TenetConfig::default();

    if let Some(value) = parsed.defaults.grace_days {
        merged.defaults.grace_days = value;
    }
    if let Some(value) = parsed.defaults.priority {
        merged.defaults.priority = value;
    }
    if let Some(value) = parsed.compile.header {
        merged.compile.header = value;
    }
    if let Some(value) = parsed.compile.include_stale {
        merged.compile.include_stale = value;
    }
    if let Some(value) = parsed.compile.segregate_stale {
        merged.compile.segregate_stale = value;
    }
    if let Some(value) = parsed.lint.check_secrets {
        merged.lint.check_secrets = value;
    }
    if let Some(value) = parsed.lint.check_filenames {
        merged.lint.check_filenames = value;
    }
    if let Some(value) = parsed.hook.install_pre_commit {
        merged.hook.install_pre_commit = value;
    }

    Ok(ConfigLoad {
        config: merged,
        warnings,
    })
}

fn check_unknown_keys<'a>(
    section: &str,
    keys: impl Iterator<Item = &'a String>,
    known: &[&str],
) -> Vec<String> {
    let known_set: HashSet<String> = known.iter().map(|value| String::from(*value)).collect();
    let mut values: Vec<String> = keys
        .filter(|value| !known_set.contains(*value))
        .map(|value| format!("unknown key in [{section}]: {value}"))
        .collect();
    values.sort();
    values
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawTopLevel {
    #[serde(default)]
    defaults: RawDefaults,
    #[serde(default)]
    compile: RawCompile,
    #[serde(default)]
    lint: RawLint,
    #[serde(default)]
    hook: RawHook,
}

#[derive(Debug, Default, Deserialize)]
struct RawDefaults {
    #[serde(default)]
    grace_days: Option<i64>,
    #[serde(default)]
    priority: Option<String>,
    #[serde(default, flatten)]
    keys: HashMap<String, toml::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct RawCompile {
    #[serde(default)]
    header: Option<String>,
    #[serde(default)]
    include_stale: Option<bool>,
    #[serde(default)]
    segregate_stale: Option<bool>,
    #[serde(default, flatten)]
    keys: HashMap<String, toml::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct RawLint {
    #[serde(default)]
    check_secrets: Option<bool>,
    #[serde(default)]
    check_filenames: Option<bool>,
    #[serde(default, flatten)]
    keys: HashMap<String, toml::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct RawHook {
    #[serde(default)]
    install_pre_commit: Option<bool>,
    #[serde(default, flatten)]
    keys: HashMap<String, toml::Value>,
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use tempfile::TempDir;

    use super::load;

    #[test]
    fn load_uses_defaults_and_overrides() {
        let temp_dir = TempDir::new().expect("tempdir");
        write_config(
            temp_dir.path(),
            r#"
[defaults]
grace_days = 30

[compile]
include_stale = false
"#,
        );

        let loaded = load(temp_dir.path()).expect("config load");

        assert_eq!(loaded.config.defaults.grace_days, 30);
        assert_eq!(loaded.config.defaults.priority, "normal");
        assert!(!loaded.config.compile.include_stale);
        assert!(loaded.config.compile.segregate_stale);
        assert!(loaded.warnings.is_empty());
    }

    #[test]
    fn load_errors_on_unknown_top_level_section() {
        let temp_dir = TempDir::new().expect("tempdir");
        write_config(
            temp_dir.path(),
            r#"
[oops]
value = true
"#,
        );

        let result = load(temp_dir.path());
        assert!(result.is_err());
    }

    fn write_config(repo_root: &Path, data: &str) {
        fs::write(repo_root.join(".tenetrc"), data).expect("write config");
    }
}
